---
##############################################################################
# SERVERS: Install and configure wireshark
##############################################################################
- hosts: servers
  name: servers install etckeeper
  gather_facts: False
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - servers
    - ansible_workstation

  pre_tasks:

    # - name: RedHat | Install a few packages for the tests
    #   yum: name={{ item }}
    #   with_items:
    #     - file
    #     - nc
    #   when: ansible_os_family == "RedHat"

    # - name: Debian | Install a few packages for the tests
    #   apt: name={{ item }}
    #   with_items:
    #     - curl
    #     - file
    #     - netcat
    #   when: ansible_os_family == "Debian"

  roles:
    # - role: boss-ansible-role-ansible-tools
    #   task: tools
    #   bossjones__user: vagrant
    #   bossjones__group: vagrant
    # - role: ansible-timezone
    #   timezone: 'America/New_York'
    #   timezone_update_hardware_clock: False
    # - role: boss-ansible-role-ntp
    #   task: install
    #   bossjones__user: vagrant
    #   bossjones__group: vagrant
    #   timezone: 'America/New_York'
    #   timezone_update_hardware_clock: False
    #   ntp_master: False

    #   # Define your ntp_master_servers
    #   ntp_master_servers:
    #     - 0.ubuntu.pool.ntp.org
    #     - 1.ubuntu.pool.ntp.org
    #     - 2.ubuntu.pool.ntp.org
    #     - 3.ubuntu.pool.ntp.org
    # - role: boss-ansible-role-journald
    # - role: boss-ansible-role-debug
    #   boss__debug__debug_variables_file: '/tmp/ansible_variables'
    #   boss__debug__dump_dir: '/etc/ansible_dumps'
    #   boss__debug__dump_type: 'seperate' # seperate

    - role: ../
